apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: spring-redis
  name: spring-redis
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: spring-redis
  type: NodePort
status:
  loadBalancer: {}
